# Generated by Django 3.2.9 on 2022-07-29 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0003_auto_20220727_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2696c5c7-0efa-11ed-a96a-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2695b423-0efa-11ed-907c-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='imageforuser',
            name='image',
            field=models.ImageField(default='../static/images/v20_51.png', upload_to='products/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('2696024a-0efa-11ed-a571-7c05079056b5'), max_length=200),
        ),
    ]
