# Generated by Django 3.2.9 on 2022-08-02 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0004_auto_20220729_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3c6b006d-1245-11ed-94c0-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3c663120-1245-11ed-9a06-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('3c6a3cf6-1245-11ed-bc95-7c05079056b5'), max_length=200),
        ),
    ]
