# Generated by Django 3.2 on 2022-10-05 19:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('oursite', '0006_auto_20220916_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructor',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ada64cd2-44e7-11ed-8eb4-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ada58961-44e7-11ed-8799-7c05079056b5'), max_length=200),
        ),
        migrations.AlterField(
            model_name='module',
            name='slug',
            field=models.SlugField(default=uuid.UUID('ada5d78e-44e7-11ed-b8d6-7c05079056b5'), max_length=200),
        ),
    ]
