# Generated by Django 3.2.9 on 2022-07-27 17:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20220727_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=uuid.UUID('b313c310-0dcf-11ed-a53b-7c05079056b5'), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=uuid.UUID('b313c312-0dcf-11ed-b227-7c05079056b5'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=uuid.UUID('b313c311-0dcf-11ed-80cd-7c05079056b5'), max_length=20),
        ),
    ]
