# Generated by Django 3.2.9 on 2022-08-02 09:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20220729_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(default=uuid.UUID('3c6c874a-1245-11ed-ab26-7c05079056b5'), max_length=250),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(default=uuid.UUID('3c6c874c-1245-11ed-8617-7c05079056b5'), max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='postal_code',
            field=models.CharField(default=uuid.UUID('3c6c874b-1245-11ed-8cb0-7c05079056b5'), max_length=20),
        ),
    ]
